name: Feature / Task
description: 새로운 기능 or 작업 이슈를 생성합니다.
title: "[Feature] "
labels:
  - feature
body:
  - type: textarea
    id: details
    attributes:
      label: 상세 요구사항 및 개발 내용
      description: 왜 이 작업이 필요한지, 배경과 목적을 적어주세요.
      placeholder: |
        - 기존 문제점
        - 개선하려는 부분
        - 개발 내용
          - [ ] 항목 1
          - [ ] 항목 2
          - [ ] 항목 3
    validations:
      required: true

  - type: textarea
    id: etc
    attributes:
      label: 기타 참고 사항
      description: 관련 문서, 화면 설계, API 명세, notion 등의 링크가 있다면 적어주세요.
      placeholder: |
        - Figma:
        - Notion:
        - API Spec:
    validations:
      required: false